//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoCalendarControl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoCalendarControl.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string ActionsDeleteTask_ButtonContent {
            get {
                return ResourceManager.GetString("ActionsDeleteTask_ButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARK AS DONE.
        /// </summary>
        public static string ActionsMarkTaskAsDone_ButtonContent {
            get {
                return ResourceManager.GetString("ActionsMarkTaskAsDone_ButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARK AS NOT DONE.
        /// </summary>
        public static string ActionsMarkTaskAsNotDone_ButtonContent {
            get {
                return ResourceManager.GetString("ActionsMarkTaskAsNotDone_ButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ActionsOKEditTask_ButtonContent {
            get {
                return ResourceManager.GetString("ActionsOKEditTask_ButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLICK TO SEE MORE.
        /// </summary>
        public static string ButtonClickToSeeMore_Down_Text {
            get {
                return ResourceManager.GetString("ButtonClickToSeeMore_Down_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLICK TO SEE MORE.
        /// </summary>
        public static string ButtonClickToSeeMore_Up_Text {
            get {
                return ResourceManager.GetString("ButtonClickToSeeMore_Up_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to type your ToDo.
        /// </summary>
        public static string ClickToTypeToDoHint {
            get {
                return ResourceManager.GetString("ClickToTypeToDoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAG AND DROP TO THE CALENDAR.
        /// </summary>
        public static string ExplanationForDragAndDrop_Text {
            get {
                return ResourceManager.GetString("ExplanationForDragAndDrop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVED.
        /// </summary>
        public static string Notification_Saved {
            get {
                return ResourceManager.GetString("Notification_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup.
        /// </summary>
        public static string OptionsButtonRestoreBackup_Content {
            get {
                return ResourceManager.GetString("OptionsButtonRestoreBackup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send backup by email.
        /// </summary>
        public static string OptionsButtonSendBackupByEmail_Content {
            get {
                return ResourceManager.GetString("OptionsButtonSendBackupByEmail_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent screen from locking.
        /// </summary>
        public static string OptionsCheckBoxForDisablingAutoScreenOff_Content {
            get {
                return ResourceManager.GetString("OptionsCheckBoxForDisablingAutoScreenOff_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTORE.
        /// </summary>
        public static string OptionsRestoreButtonGo_Content {
            get {
                return ResourceManager.GetString("OptionsRestoreButtonGo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy/paste backup data to the field below, then click RESTORE:.
        /// </summary>
        public static string OptionsRestoreExplanation_Text {
            get {
                return ResourceManager.GetString("OptionsRestoreExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS:.
        /// </summary>
        public static string OptionsTitle_Text {
            get {
                return ResourceManager.GetString("OptionsTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIGH PRIORITY.
        /// </summary>
        public static string PriorityHigh_RadioButtonContent {
            get {
                return ResourceManager.GetString("PriorityHigh_RadioButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string PriorityInfo_RadioButtonContent {
            get {
                return ResourceManager.GetString("PriorityInfo_RadioButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOW PRIORITY.
        /// </summary>
        public static string PriorityLow_RadioButtonContent {
            get {
                return ResourceManager.GetString("PriorityLow_RadioButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORMAL.
        /// </summary>
        public static string PriorityNormal_RadioButtonContent {
            get {
                return ResourceManager.GetString("PriorityNormal_RadioButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your ToDo.
        /// </summary>
        public static string TypeToDoHint {
            get {
                return ResourceManager.GetString("TypeToDoHint", resourceCulture);
            }
        }
    }
}
